name: my_store
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1

  ## -- STATE MANAGEMENT
  get: ^4.7.2
  get_storage: ^2.1.1

  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.1

  ## -- OTP TEXT FIELD PACKAGE
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1

  ## -- FIREBASE PACKAGES
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.6
  firebase_crashlytics: ^4.3.6


  ## -- ICON PACKAGES
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  line_awesome_flutter: ^3.0.1

  ## -- Utility PACKAGES
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  badges: ^3.1.2
  shimmer: ^3.0.0
  readmore: ^3.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.1
  country_code_picker: ^3.3.0
  flutter_native_splash: ^2.4.6

  # Notification
  flutter_local_notifications: ^19.2.1

  supabase_flutter: ^2.9.0


  http: any
  flutter_rating_bar: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/brands/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/icons/payment_methods/
    - assets/images/products/
    - assets/images/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/paypal.png

# Splash screen has been added in the 'splash.yaml' file in main project directory